function build_a43_simulink_model()
%BUILD_A43_SIMULINK_MODEL 按 A43 数学建模文章自动搭建 Simulink 验证模型。
%
% 模型内容：
% 1. OpenLoopPlant: H(s)=1/(s^2-g/L)，无控制倒立摆；
% 2. ClosedLoopPlant: H(s)=1/(s^2+(k2/L)s+(k1-g)/L)，加入 PD 后的闭环系统；
% 3. 同一个扰动脉冲输入，比较两者角度响应。

a43_params;

model = 'a43_balance_model_verification';

if bdIsLoaded(model)
    close_system(model, 0);
end

new_system(model);
open_system(model);

set_param(model, ...
    'Solver', 'ode45', ...
    'StopTime', num2str(Tstop), ...
    'ReturnWorkspaceOutputs', 'on');

%% 输入扰动：用 Step - Step 组成宽度为 1s 的脉冲
add_block('simulink/Sources/Step', [model '/PushStart'], ...
    'Time', num2str(disturb_time), ...
    'Before', '0', ...
    'After', num2str(disturb_amp), ...
    'Position', [40 80 80 110]);

add_block('simulink/Sources/Step', [model '/PushEnd'], ...
    'Time', num2str(disturb_time + disturb_width), ...
    'Before', '0', ...
    'After', num2str(disturb_amp), ...
    'Position', [40 150 80 180]);

add_block('simulink/Math Operations/Sum', [model '/PulseDisturbance'], ...
    'Inputs', '+-', ...
    'Position', [130 105 160 145]);

%% 开环倒立摆传递函数
add_block('simulink/Continuous/Transfer Fcn', [model '/OpenLoop_Hs_1_over_s2_minus_g_over_L'], ...
    'Numerator', '[1]', ...
    'Denominator', mat2str(open_den), ...
    'Position', [245 70 430 120]);

%% 加 PD 后的闭环传递函数
add_block('simulink/Continuous/Transfer Fcn', [model '/ClosedLoop_PD'], ...
    'Numerator', '[1]', ...
    'Denominator', mat2str(closed_den), ...
    'Position', [245 155 430 205]);

%% 输出到工作区
add_block('simulink/Sinks/To Workspace', [model '/open_angle'], ...
    'VariableName', 'open_angle', ...
    'SaveFormat', 'StructureWithTime', ...
    'Position', [520 80 620 110]);

add_block('simulink/Sinks/To Workspace', [model '/closed_angle'], ...
    'VariableName', 'closed_angle', ...
    'SaveFormat', 'StructureWithTime', ...
    'Position', [520 165 620 195]);

add_block('simulink/Sinks/To Workspace', [model '/disturbance'], ...
    'VariableName', 'disturbance', ...
    'SaveFormat', 'StructureWithTime', ...
    'Position', [245 255 345 285]);

%% Scope 方便你打开模型后直接看波形
add_block('simulink/Signal Routing/Mux', [model '/Mux'], ...
    'Inputs', '3', ...
    'Position', [520 250 545 315]);

add_block('simulink/Sinks/Scope', [model '/Scope_Angle_Compare'], ...
    'Position', [620 245 760 320]);

%% 连线
add_line(model, 'PushStart/1', 'PulseDisturbance/1');
add_line(model, 'PushEnd/1', 'PulseDisturbance/2');

add_line(model, 'PulseDisturbance/1', 'OpenLoop_Hs_1_over_s2_minus_g_over_L/1');
add_line(model, 'PulseDisturbance/1', 'ClosedLoop_PD/1');
add_line(model, 'PulseDisturbance/1', 'disturbance/1');

add_line(model, 'OpenLoop_Hs_1_over_s2_minus_g_over_L/1', 'open_angle/1');
add_line(model, 'ClosedLoop_PD/1', 'closed_angle/1');

add_line(model, 'OpenLoop_Hs_1_over_s2_minus_g_over_L/1', 'Mux/1');
add_line(model, 'ClosedLoop_PD/1', 'Mux/2');
add_line(model, 'PulseDisturbance/1', 'Mux/3');
add_line(model, 'Mux/1', 'Scope_Angle_Compare/1');

save_system(model, fullfile(pwd, [model '.slx']));
fprintf('Generated %s\n', fullfile(pwd, [model '.slx']));
end
